Settings improvements 2
livingtongues/living-dictionaries pull request #148
Opened 2022-04-17 23:55 UTC by jacob-8

#### Relevant Issues
#112, #104, #105

#### Summarize what changed in this PR (for developers)
Made reusable component for editing coordinates

#### Summarize changes in this PR (for public-facing changelog)

#### How can the changes be tested? Please also provide applicable links using preview deployments once they are available (will require editing this message once the preview deployment is ready).
http://localhost:3041/achi/settings
http://localhost:3041/create-dictionary
http://localhost:3041/admin/dictionaries

2022-04-19 17:43 UTC, Danble commented
@jacob-8  Wouldn't be better if in `packages\site\src\sveltefirets\index.ts` we change line 33. Instead of import `./loader` we impport from `@ld/parts/src/lib/maps/loader`? Then we can delete the duplicate file loader from site.

2022-04-19 17:51 UTC, Danble requested changes
@jacob-8  Wouldn't be better if in `packages\site\src\sveltefirets\index.ts` we change line 33. Instead of import `./loader` we import from `@ld/parts/src/lib/maps/loader`? Then we can delete the duplicate file loader from site.
I tested and it works! But we also need to change line 12 of `packages\site\src\sveltefirets\components\FirebaseUiAuth.svelte`

2022-04-19 18:03 UTC, Danble reviewed
I also spotted a very weird bug that seems to happen when I interact with the coordinates map (If I save or remove the coordinates) when I go back to the home page, this happens:
![image](https://user-images.githubusercontent.com/43384963/164066556-53dcef11-df20-4c06-8f27-700cd01b587a.png)
It is happening both in my local environment and in the vercel link, but it triggers more easily in my local env, I have no idea why.

2022-04-19 19:18 UTC, Danble requested changes

2022-04-19 19:18 UTC, Danble commented on packages/site/src/routes/create-dictionary.svelte
> +      <EditableCoordinatesField
@jacob-8  It seems to me you forgot to add `{t}` here

2022-04-19 19:18 UTC, Danble commented on packages/site/src/routes/[dictionaryId]/settings.svelte
> +    <EditableCoordinatesField
@jacob-8 Here we also need the i18n: `t={_}`, right?

2022-04-26 00:01 UTC, jacob-8 commented
> a very weird bug that seems to happen when I interact with the coordinates map

It was caused by my use of windi:global in Modal.svelte in svelte-pieces. Fixed in v1.0.10.

2022-04-26 00:04 UTC, merged